apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-spire
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "spire.name" . }}-server
  policyTypes:
    - Ingress
  ingress:
    - from:
      # BSS Access to request tokens for compute and UANs
      - namespaceSelector:
          matchLabels:
            name: services
        podSelector:
          matchLabels:
            app.kubernetes.io/name: cray-bss
      # request-ncn-join-token joins kubernetes NCNs via a daemonset
      - namespaceSelector:
          matchLabels:
            name: spire
        podSelector:
          matchLabels:
            name: request-ncn-join-token
      ports:
        - protocol: TCP
          port: 54440
    # Allow access to spire server from anywhere.
    - from: []
      ports:
        - protocol: TCP
          port: 8081
