apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cray-sysmgmt-health-spire-server
  namespace: sysmgmt-health
  labels:
    release: cray-sysmgmt-health
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - spire
  selector:
    matchLabels:
      app.kubernetes.io/name: spire-server
