#
# MIT License
#
# (C) Copyright [2022] Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
{{- if .Values.bundle.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spire.fullname" . }}-bundle
  labels:
    app.kubernetes.io/name: {{ template "spire.name" . }}-bundle
    {{- include "spire.common-labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.bundle.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "spire.name" . }}-bundle
  template:
    metadata:
      annotations:
      {{- with .Values.bundle.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ template "spire.name" . }}-bundle
    spec:
      serviceAccountName: {{ include "spire.name" . }}-bundle
      affinity:
          podAntiAffinity:
             preferredDuringSchedulingIgnoredDuringExecution:
               - weight: 1
                 podAffinityTerm:
                   labelSelector:
                     matchExpressions:
                     - key: app
                       operator: In
                       values:
                       - {{ include "spire.name" . }}-bundle
                   topologyKey: kubernetes.io/hostname
      containers:
        - name: {{ template "spire.name" . }}-bundle
          image: "{{ .Values.bundle.image.repository }}:{{ .Values.bundle.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.bundle.image.pullPolicy }}
          args: ["-config", "/run/spire/config/spire-bundle.conf"]
          env:
            - name: DOMAIN
              value: "{{ .Values.trustDomain }}"
            - name: SERVER
              value: "{{ .Values.server.lbIP }}"
            - name: BUNDLE
              value: "/run/spire/bundle/bundle.crt"
          ports:
          - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
          volumeMounts:
            - name: spire-bundle
              mountPath: /run/spire/bundle
              readOnly: true
      volumes:
        - name: spire-bundle
          configMap:
            name: spire-bundle
{{- end }}
