# Default values for spire-intermediate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""

global:
  chart:
    name: ""     # set at deploy time automatically, no need to ever set explicitly
    version: ""  # set at deploy time automatically, no need to ever set explicitly

image:
  repository: artifactory.algol60.net/csm-docker/stable/spire-intermediate
  tag: 0.3.1
  pullPolicy: IfNotPresent

namespaces:
  - spire

vaultPKIPath: pki_common
