#
# MIT License
#
# (C) Copyright [2022] Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "spire.fullname" . }}-agent
  labels:
    app.kubernetes.io/name: {{ template "spire.name" . }}-agent
    {{- include "spire.common-labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "spire.name" . }}-agent
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      {{- with .Values.agent.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ template "spire.name" . }}-agent
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: {{ template "spire.name" . }}-agent
      initContainers:
        - name: init-setperms
          image: "{{ .Values.agent.init2.repository }}:{{ .Values.agent.init2.tag }}"
          imagePullPolicy: {{ .Values.agent.init2.pullPolicy }}
          command:
            - '/bin/sh'
          args:
            - '-x'
            - '-c'
            - 'chown -R 65534:65534 /run/spire/sockets'
          volumeMounts:
            - name: {{ template "spire.name" . }}-socket
              mountPath: /run/spire/sockets
              readOnly: false
        - name: init
          # This is a small image with wait-for-it, choose whatever image
          # you prefer that waits for a service to be up. This image is built
          # from https://github.com/Cray-HPE/container-images
          image: "{{ .Values.agent.init.repository }}:{{ .Values.agent.init.tag }}"
          imagePullPolicy: {{ .Values.agent.init.pullPolicy }}
          args: ["-t", "30", "spire-server:{{ .Values.server.port }}"]
      containers:
        - name: {{ template "spire.name" . }}
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            runAsNonRoot: true
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          args: ["-config", "/run/spire/config/spire-agent.conf"]
          volumeMounts:
            - name: {{ template "spire.name" . }}-config
              mountPath: /run/spire/config
              readOnly: true
            - name: spire-bundle
              mountPath: /run/spire/bundle
              readOnly: true
            - name: {{ template "spire.name" . }}-socket
              mountPath: /run/spire/sockets
              readOnly: false
          livenessProbe:
            exec:
              command: ["/opt/spire/bin/spire-agent", "healthcheck", "-socketPath", "/run/spire/sockets/agent.sock"]
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
      volumes:
        - name: {{ template "spire.name" . }}-config
          configMap:
            name: {{ template "spire.name" . }}-agent-config
        - name: spire-bundle
          configMap:
            name: spire-bundle
        - name: {{ template "spire.name" . }}-socket
          hostPath:
            path: {{ .Values.agent.wlSocket }}
            type: DirectoryOrCreate
