apiVersion: v2
name: spire
version: 1.6.0
description: A Helm chart for spire
home: https://github.com/Cray-HPE/cray-spire
dependencies:
  - name: cray-service
    version: ~7.0.0
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
maintainers:
  - name: kburns-hpe
appVersion: 0.12.2
annotations:
  artifacthub.io/images: |-
    - name: cray-spire-jwks
      image: artifactory.algol60.net/csm-docker/stable/cray-spire-jwks:0.1.1
    - name: spire-bundle
      image: artifactory.algol60.net/csm-docker/stable/spire-bundle:0.2.0
    - name: spire-tokens
      image: artifactory.algol60.net/csm-docker/stable/spire-tokens:2.0.0
    - name: wait-for-it
      images: artifactory.algol60.net/csm-docker/stable/sdlc-ops/wait-for-it:20211201
    - name: alpine
      image: alpine:3.14
    - name: curl
      images: artifactory.algol60.net/csm-docker/stable/docker.io/curlimages/curl:7.80.0
    - name: nginx
      image: artifactory.algol60.net/csm-docker/stable/docker.io/library/nginx:1.18.0-alpine
    - name: pause
      images: k8s.gcr.io/pause:3.2
    - name: postgres
      image: artifactory.algol60.net/csm-docker/stable/docker.io/library/postgres:13.2-alpine
    - name: postgres-db-backup
      image: artifactory.algol60.net/csm-docker/stable/cray-postgres-db-backup:0.2.0
    - name: spire-server
      image: artifactory.algol60.net/csm-docker/stable/gcr.io/spiffe-io/spire-server:0.12.2
    - name: spire-agent
      image: artifactory.algol60.net/csm-docker/stable/gcr.io/spiffe-io/spire-agent:0.12.2
  artifacthub.io/license: MIT
