nameOverride: ""

global:
  chart:
    name: ""     # set at deploy time automatically, no need to ever set explicitly
    version: ""  # set at deploy time automatically, no need to ever set explicitly

trustDomain: shasta

server:
  replicaCount: 3
  lbIP: "10.92.100.82"
  fqdn: spire.local
  port: 8081
  logLevel: INFO
  jwtIssuer: http://spire.local/shasta/vshastaio
  caTTL: 2160h
  svidDefaultTTL: 12h
  database: spire
  maxOpenDBConns: 20
  registrationPort: 54440
  priorityClassName: csm-high-priority-service
  tokenService:
    computeEntry: /compute/tenant1
    computeClusterEntry: /compute
    ncnEntry: /ncn/tenant1
    ncnClusterEntry: /ncn
    storageEntry: /storage/tenant1
    storageClusterEntry: /storage
    uanEntry: /uan/tenant1
    uanClusterEntry: /uan
    tokenTTL: 10800
    enableXNameWorkloads: false
  annotations: {}

  init:
    repository: artifactory.algol60.net/csm-docker/stable/sdlc-ops/wait-for-it
    tag: "20211201"
    pullPolicy: IfNotPresent

  init2:
    repository: alpine
    tag: 3.14
    pullPolicy: IfNotPresent

  image:
    repository: artifactory.algol60.net/csm-docker/stable/gcr.io/spiffe-io/spire-server
    tag: 0.12.2
    pullPolicy: IfNotPresent

  registration:
    repository: artifactory.algol60.net/csm-docker/stable/spire-tokens
    tag: 2.0.0
    pullPolicy: IfNotPresent

  persistentVolume:
    accessModes:
    - ReadWriteOnce
    size: 1Gi
    storageClass: ""

cray-service:
  type: ""
  nameOverride: spire
  service:
    enabled: false
  sqlCluster:
    enabled: true
    instanceCount: 3
    postgresVersion: "11"
    volumeSize: 60Gi
    podPriorityClassName: csm-high-priority-service
    users:
      spire: []
    databases:
      spire: spire
    tls:
      issuer: cert-manager-issuer-common
    resources:
      limits:
        cpu: "8"
        memory: 8Gi
      requests:
        cpu: "4"
        memory: 4Gi
    waitForItJob: false
    connectionPooler:
      enabled: true
    parameters:
      idle_in_transaction_session_timeout: "5000"
      statement_timeout: "60000"
    backup:
      enabled: true
      schedule: "10 3 * * *"  # Once per day at 3:10AM

tls:
  issuer: cert-manager-issuer-common

agent:
  logLevel: INFO
  wlSocket: /run/spire/vshastaio/sockets

  init:
    repository: artifactory.algol60.net/csm-docker/stable/sdlc-ops/wait-for-it
    tag: "20211201"
    pullPolicy: IfNotPresent

  init2:
    repository: alpine
    tag: 3.14
    pullPolicy: IfNotPresent

  image:
    repository: artifactory.algol60.net/csm-docker/stable/gcr.io/spiffe-io/spire-agent
    tag: 0.12.2
    pullPolicy: IfNotPresent

jwks:
  domain: vshasta.io
  uriPrefix: spire-jwks-vshastaio
  logLevel: INFO
  port: 80
  replicaCount: 3
  priorityClassName: csm-high-priority-service

  image:
    repository: artifactory.algol60.net/csm-docker/stable/cray-spire-jwks
    tag: 0.1.1
    pullPolicy: IfNotPresent

  nginx:
    repository: artifactory.algol60.net/csm-docker/stable/docker.io/library/nginx
    tag: 1.18.0-alpine
    pullPolicy: IfNotPresent

bundle:
  enabled: false
  uriPrefix: spire-bundle
  logLevel: INFO
  port: 8080
  replicaCount: 3

  image:
    repository: artifactory.algol60.net/csm-docker/stable/spire-bundle
    tag: 0.2.0
    pullPolicy: IfNotPresent

bss:
  endpoint: http://cray-bss.services.svc.cluster.local/boot/v1/bootparameters
  curl:
    repository: artifactory.algol60.net/csm-docker/stable/docker.io/curlimages/curl
    tag: 7.80.0

ncn:
  url: https://spire-tokens.spire:54440/api/token
  filename: join_token
  path: /root/spire/conf
  init:
    repository: alpine
    tag: 3.14
  curl:
    repository: artifactory.algol60.net/csm-docker/stable/docker.io/curlimages/curl
    tag: 7.80.0
  pause:
    repository: k8s.gcr.io/pause
    tag: 3.2
